# Read the documentation: https://symfony.com/doc/master/bundles/FOSRestBundle/index.html
fos_rest:
    param_fetcher_listener:  true
    allowed_methods_listener:  true
#    routing_loader: true
#    body_listener: true
#    body_converter:
#        enabled: false
    view:
        view_response_listener:  true
    serializer:
        serialize_null: true
    format_listener:
        rules:
            - { path: ^/api, prefer_extension: true, fallback_format: json, priorities: [json] }
            - { path: '^/', stop: true }
    exception:
        enabled: true
        serializer_error_renderer: true
        messages:
            'Symfony\Component\HttpKernel\Exception\HttpException': true